# Generated by Django 3.1.6 on 2021-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
