# Generated by Django 3.1.6 on 2021-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210514_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
