# Generated by Django 3.1.6 on 2021-05-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210514_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.artist'),
        ),
    ]
