# Generated by Django 3.1.6 on 2021-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_album_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
