# Generated by Django 3.1.6 on 2021-05-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210515_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
