# Generated by Django 3.1.6 on 2021-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_artist_artist_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='stars',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review_msg',
            field=models.TextField(null=True),
        ),
    ]
