# Generated by Django 3.1.6 on 2021-05-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210518_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='stars',
        ),
    ]
