# Generated by Django 3.1.6 on 2021-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_album_avg_rating_alb'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='avg_rating_alb_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
